### ISSUE TITLE
بهبود تماس

### ISSUE THREAD

**Issue by RaziPour1993** [RooyeKhat-Media/iGap-iOS#22]
سلام
بهتره برای تماس صوتی از لایبری های خود اپل استفاده کنید
CallKit
 برای نوتیفیکیشن هم از لایبری
PushKIt

لینک زیر کامل توضیح داده همه چیزهایی که نیاز دارید
https://websitebeaver.com/callkit-swift-tutorial-super-easy

**Comment by saeedrooyekhat** [comment]
Soon the [PushKit](https://developer.apple.com/documentation/pushkit?changes=_5) framework will be added to the program and users can receive calls even when the application is closed.

also due to the c1f3b0cb22953a1652a0378084070c724e6cf730 now users can receive message notifications even when the application is closed. of course this feature will be added in the next app release.
